# This rule is not used by the project soyplane itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the opentofu.soyplane.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: soyplane
    app.kubernetes.io/managed-by: kustomize
  name: opentofu-tofustack-editor-role
rules:
- apiGroups:
  - opentofu.soyplane.io
  resources:
  - tofustacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentofu.soyplane.io
  resources:
  - tofustacks/status
  verbs:
  - get
