# This rule is not used by the project soyplane itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to opentofu.soyplane.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: soyplane
    app.kubernetes.io/managed-by: kustomize
  name: opentofu-tofustack-viewer-role
rules:
- apiGroups:
  - opentofu.soyplane.io
  resources:
  - tofustacks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opentofu.soyplane.io
  resources:
  - tofustacks/status
  verbs:
  - get
